export const JOIN_ROOM = 'JOIN_ROOM';
export const EXIT_ROOM = 'EXIT_ROOM';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const SEND_IMAGE = 'SEND_IMAGE';
export const RECEIVE_IMAGE = 'RECEIVE_IMAGE';

export const RECEIVE_USER_LIST = 'RECEIVE_USER_LIST';
export const RECEIVE_USER_INFO_WITH_SOCKET_ID = 'RECEIVE_USER_INFO_WITH_SOCKET_ID';

export const GET_EXIST_ROOM_LIST = 'GET_EXIST_ROOM_LIST';
export const RECEIVE_EXIST_ROOM_LIST = 'RECEIVE_EXIST_ROOM_LIST';



